### ISSUE TITLE
Faraday ReadTimeout

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#44]
Reported:

Started GET "/article/edsgao__edsgcl_479443962" for 127.0.0.1 at 2017-07-06 11:30:27 -0700
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ArticleController#show as HTML
  Parameters: {"id"=>"edsgao__edsgcl_479443962"}
CREATE SESSION CALLER: "bl-repo-find"
CALLER OPTIONS: {:guest=>true, :session_token=>"57924134-b507-4afe-a256-b591ea76bd72.A/dppBmlQH/R28bXp3M7tUGHiuYvlJ241l0Yi2R0ADc=", :caller=>"bl-repo-find", :user=>"", :pass=>"", :profile=>"", :debug=>true}
AUTH TOKEN: "ACNzCTbOk0WE6iuF1dN-CfcfUR7Ff1legpR7IkN1c3RvbWVySWQiOiJzNDM5Mjc5OCIsIkdyb3VwSWQiOiJ0cmlhbCJ9"
SESSION TOKEN: "57924134-b507-4afe-a256-b591ea76bd72.A/dppBmlQH/R28bXp3M7tUGHiuYvlJ241l0Yi2R0ADc="
Completed 500 Internal Server Error in 60117ms (ActiveRecord: 0.0ms)
  
Faraday::TimeoutError (Net::ReadTimeout):
  
app/models/eds/repository.rb:45:in `find'
app/services/eds/search_service.rb:41:in `fetch_one'
app/services/eds/search_service.rb:36:in `fetch'
app/controllers/article_controller.rb:145:in `show'

**Comment by bmckinney** [comment]
Configurable faraday timeout. See: https://github.com/ebsco/edsapi-ruby/commit/da699a5a32ea345e8751a28189909bc3bb88facf
